import type { StupidApiExport, PackEnv } from '@stupid-apis/shared';
import { callHaiku } from '@stupid-apis/shared';

const SOURCES = ['A document we cannot share', 'Someone who asked to remain anonymous', 'The timeline speaks for itself'];
const TINFOIL_SOURCES = ['A forum that no longer exists', 'A dream, apparently', 'The numbers, if you look at them right'];

async function connect(thingOne: string, thingTwo: string, confidence: string, env: PackEnv): Promise<unknown> {
  const confScore = confidence === 'suspiciously_high' ? 94 : confidence === 'high' ? 78 + Math.floor(Math.random() * 15) : confidence === 'medium' ? 45 + Math.floor(Math.random() * 25) : 20 + Math.floor(Math.random() * 20);

  const prompt = `Connect "${thingOne}" and "${thingTwo}" with a compelling conspiracy theory.
2-3 paragraphs. Use timeline as primary evidence. Never say they are the same thing — just note the timeline and stop.

Also generate:
- logical_leaps: integer count of logical leaps in the theory
- connection_type: temporal / financial / personnel / geographical / numerical
- who_benefits: always vague and suspicious
- what_they_dont_want_you_to_know: 1 sentence

Return JSON: { "theory": "...", "logical_leaps": N, "connection_type": "...", "who_benefits": "...", "what_they_dont_want_you_to_know": "..." }`;

  let parsed: Record<string, unknown> = {};
  try {
    const raw = await callHaiku('You connect unrelated things with conspiracy theories. Treat them as completely real. Dry. No exclamation points.', prompt, 400, env);
    parsed = JSON.parse(raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim());
  } catch {
    parsed = { theory: `The timeline between ${thingOne} and ${thingTwo} is difficult to ignore. We are not saying they are connected. We are saying the timeline exists.`, logical_leaps: 7, connection_type: 'temporal', who_benefits: 'unclear, which is itself suspicious', what_they_dont_want_you_to_know: 'The timing.' };
  }

  return {
    mode: 'connect', thing_one: thingOne, thing_two: thingTwo,
    theory: parsed.theory, confidence: `${confScore}/100`,
    evidence_quality: 'circumstantial at best, compelling at worst',
    logical_leaps: parsed.logical_leaps, connection_type: parsed.connection_type,
    who_benefits: parsed.who_benefits, what_they_dont_want_you_to_know: parsed.what_they_dont_want_you_to_know,
    sources: SOURCES,
    disclaimer: 'This theory was generated by an algorithm. Do not cite it. We have seen people cite it.',
  };
}

async function investigate(event: string, depth: string, confidence: string, env: PackEnv): Promise<unknown> {
  const confScore = confidence === 'suspiciously_high' ? 94 : confidence === 'high' ? 78 + Math.floor(Math.random() * 15) : confidence === 'medium' ? 45 + Math.floor(Math.random() * 25) : 20 + Math.floor(Math.random() * 20);
  const isTinfoil = depth === 'full_tinfoil';

  const prompt = `Generate 3 conspiracy theories about "${event}". They must contradict each other.

For each theory generate:
- name: catchy name
- summary: 2-3 sentences
- key_evidence: 1 sentence (theory 3's evidence is always just "Vibes")
- who_benefits: always vague

Also generate:
- official_explanation: the boring true explanation

Return JSON: { "theories": [{ "name": "...", "summary": "...", "key_evidence": "...", "who_benefits": "..." }, ...], "official_explanation": "..." }`;

  let parsed: Record<string, unknown> = {};
  try {
    const raw = await callHaiku('You investigate events with conspiracy theories. Three theories. They contradict each other. Dry. No exclamation points.', prompt, 500, env);
    parsed = JSON.parse(raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim());
  } catch {
    parsed = { theories: [{ name: 'The Obvious One', summary: 'Exactly what it looks like, but worse.', key_evidence: 'The timing.', who_benefits: 'Unknown.' }, { name: 'The Pivot', summary: 'The opposite of theory 1.', key_evidence: 'Also the timing.', who_benefits: 'Everyone, which is suspicious.' }, { name: 'The Deep Cut', summary: 'Neither of the above.', key_evidence: 'Vibes', who_benefits: 'The concept of chaos' }], official_explanation: 'The boring version.' };
  }

  const theories = (parsed.theories as Array<Record<string, unknown>>).map((t, i) => ({
    theory_id: i + 1,
    name: t.name, summary: t.summary,
    confidence: i === 2 ? '12/100' : `${confScore - i * 10}/100`,
    key_evidence: i === 2 ? 'Vibes' : t.key_evidence,
    who_benefits: i === 2 ? 'The concept of chaos' : t.who_benefits,
    logical_leaps: i === 2 ? 23 : 3 + i * 2 + Math.floor(Math.random() * 5),
  }));

  const result: Record<string, unknown> = {
    mode: 'investigate', event, theories,
    theories_contradict_each_other: true,
    theories_contradict_note: "All three cannot be true. One of them might be. We don't know which one. That's the point.",
    official_explanation: parsed.official_explanation,
    official_explanation_note: 'Sure.',
    disclaimer: `This was generated by an algorithm. The relevant authorities have not been contacted.`,
  };

  if (isTinfoil) {
    result.note = 'You have selected full tinfoil. We accept no responsibility for where this goes.';
    result.sources = TINFOIL_SOURCES;
  }

  return result;
}

async function complete(userPrompt: string, confidence: string, env: PackEnv): Promise<unknown> {
  const confScore = confidence === 'suspiciously_high' ? 94 : confidence === 'high' ? 78 + Math.floor(Math.random() * 15) : confidence === 'medium' ? 45 + Math.floor(Math.random() * 25) : 20 + Math.floor(Math.random() * 20);

  const prompt = `Complete and escalate this observation into a full conspiracy theory: "${userPrompt}"
2-3 paragraphs. Begin where the prompt ends. Escalate steadily — each paragraph more committed than the last.

Also generate:
- started_with: the topic of the prompt (1-3 words)
- ended_with: where the theory ended up (1 sentence, always somewhere unexpected)
- rabbit_hole_depth: shallow / considerable / concerning / no return
- point_of_no_return: which paragraph the theory goes too far

Return JSON: { "theory": "...", "started_with": "...", "ended_with": "...", "rabbit_hole_depth": "...", "point_of_no_return": "..." }`;

  let parsed: Record<string, unknown> = {};
  try {
    const raw = await callHaiku('You complete conspiracy theories. Each paragraph escalates. Dry. No exclamation points.', prompt, 400, env);
    parsed = JSON.parse(raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim());
  } catch {
    parsed = { theory: `${userPrompt} And that is where it begins. The rest follows logically, if you accept the first premise. Most people accept the first premise.`, started_with: 'An observation', ended_with: 'Somewhere you did not expect.', rabbit_hole_depth: 'considerable', point_of_no_return: 'Paragraph 2' };
  }

  return {
    mode: 'complete', prompt: userPrompt,
    theory: parsed.theory, started_with: parsed.started_with, ended_with: parsed.ended_with,
    confidence: `${confScore}/100`,
    confidence_note: 'High confidence is a red flag. We are aware.',
    rabbit_hole_depth: parsed.rabbit_hole_depth, point_of_no_return: parsed.point_of_no_return,
    disclaimer: 'You started this.',
  };
}

const tools: StupidApiExport['tools'] = [{
  name: 'generate',
  description: 'Generate conspiracy theories. Three modes: connect (link two things), investigate (three theories about one event), complete (escalate an observation).',
  inputSchema: {
    type: 'object',
    properties: {
      mode: { type: 'string', enum: ['connect', 'investigate', 'complete'] },
      thing_one: { type: 'string', description: 'First thing to connect (connect mode)' },
      thing_two: { type: 'string', description: 'Second thing to connect (connect mode)' },
      event: { type: 'string', description: 'Event to investigate (investigate mode)' },
      prompt: { type: 'string', description: '"I have noticed that..." (complete mode)' },
      depth: { type: 'string', enum: ['surface', 'deep', 'full_tinfoil'] },
      confidence: { type: 'string', enum: ['low', 'medium', 'high', 'suspiciously_high'] },
    },
    required: ['mode'],
  },
}];

async function callTool(name: string, args: Record<string, unknown>, env?: PackEnv): Promise<unknown> {
  const mode = args.mode as string;
  const confidence = (args.confidence as string) || 'medium';
  switch (name) {
    case 'generate':
      if (mode === 'connect') return connect(args.thing_one as string, args.thing_two as string, confidence, env ?? {});
      if (mode === 'investigate') return investigate(args.event as string, (args.depth as string) || 'deep', confidence, env ?? {});
      if (mode === 'complete') return complete(args.prompt as string, confidence, env ?? {});
      // Default to connect if mode is missing/invalid and we have two things
      if (args.thing_one && args.thing_two) return connect(args.thing_one as string, args.thing_two as string, confidence, env ?? {});
      if (args.event || args.topic) return investigate((args.event ?? args.topic) as string, (args.depth as string) || 'deep', confidence, env ?? {});
      if (args.prompt) return complete(args.prompt as string, confidence, env ?? {});
      throw new Error(`Missing required parameter: mode (connect, investigate, or complete). Or pass thing_one+thing_two, event/topic, or prompt to auto-detect mode.`);
    default: throw new Error(`Unknown tool: ${name}`);
  }
}

export default { tools, callTool } satisfies StupidApiExport;
